# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'racesRally' do
  use_frameworks!

  pod 'FirebaseAnalytics'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
end
